# -*- coding: utf-8 -*-
"""
Hand-transcribed line items from BoQ_CBRI_Principals_Residence.pdf
(Central Building Research Institute, Roorkee - "Principal's Residence
(General-Modified)", Schedule 'A', DSR 1989).

The PDF is a dot-matrix scan with NO text layer (confirmed empty extraction
via PyMuPDF), so items were transcribed by visually reading each of the 13
rendered pages at 300dpi. Quantities were double-checked against the
handwritten quantity column. See APPROACH.md for the full extraction method.

Each entry corresponds to one numbered Sl.No. (1-64) in the BoQ. Items with
multiple lettered sub-quantities (i, ii, iii ...) carry a `sub_items` list;
these are expanded into separate Material Passport rows because each
sub-item is a physically distinct material/quantity.
"""

# Sub-head groupings inferred from DSR 1989 chapter numbers, consistent with
# the convention shown by the template's own example rows (Sub-Head I = Earth
# Work, II = Concrete Work, III = RCC Work).
SUBHEAD_BY_CHAPTER = {
    2: "Sub-Head - I, Earth Work",
    4: "Sub-Head - II, Concrete Work",
    5: "Sub-Head - III, RCC Work",
    6: "Sub-Head - IV, Brick Work",
    9: "Sub-Head - V, Wood & Joinery Work",
    10: "Sub-Head - VI, Steel & Metal Work",
    11: "Sub-Head - VII, Flooring",
    12: "Sub-Head - VIII, Roofing & Roof Drainage",
    13: "Sub-Head - IX, Finishing (Plaster/Paint/Polish)",
    16: "Sub-Head - X, Sanitary & Plinth Protection",
}


def subhead_for(dsr_code: str) -> str:
    if not dsr_code or dsr_code in ("N.S.I.", "N/A", ""):
        return "Sub-Head - Unclassified (No DSR code given)"
    first = dsr_code.split("/")[0].strip()
    try:
        chapter = int(first.split(".")[0])
    except ValueError:
        return "Sub-Head - Unclassified (No DSR code given)"
    return SUBHEAD_BY_CHAPTER.get(chapter, "Sub-Head - Unclassified")


# RAW_ITEMS: one dict per Sl.No. in the scan.
RAW_ITEMS = [
    dict(sl="1", dsr="2.8", qty=32.0, unit="Cu.m",
         desc="Earth work in excavation in foundation trenches or drains not exceeding 1.5 m in width or 10 Sq.m on plan including dressing of sides and ramming of bottoms, lift upto 1.5 m including getting out the excavated soil and disposal of surplus excavated soil as directed within a lead of 50 m in all types of soil except rocks.",
         discipline="Civil & Sitework", material="Earthwork (excavation)", category="Earthwork",
         excluded=True, comment="[EXCLUDED] earth + labour; no persisting building material, negligible embodied carbon"),
    dict(sl="2", dsr="2.26", qty=12.0, unit="Cu.m",
         desc="Filling available excavated earth (excluding rock) in trenches, plinth, sides of foundations etc. in layers not exceeding 20 cm in depth consolidating each deposited layer by ramming & watering, lead upto 50 m and lift upto 1.5 m.",
         discipline="Civil & Sitework", material="Earthwork (backfill, reused excavated soil)", category="Earthwork",
         excluded=True, comment="[EXCLUDED] reused native soil, no new material, negligible embodied carbon"),
    dict(sl="3", dsr="2.28", qty=11.0, unit="Cu.m",
         desc="Filling the plinth with fine sand under floors including watering, ramming consolidating and dressing complete.",
         discipline="Civil & Sitework", material="Fine sand (plinth filling)", category="Earthwork Fill",
         classification="Aggregates > Sand > Fine sand (plinth fill)"),
    dict(sl="4", dsr="2.29.1", qty=1.4, unit="100 Sq.m",
         desc="Surface dressing of the ground including removing vegetation, and inequalities not exceeding 15 cm deep and disposal of rubbish, lead upto 50 m and lift upto 1.5 m in soft/loose soil.",
         discipline="Civil & Sitework", material="Earthwork (surface dressing)", category="Earthwork",
         excluded=True, comment="[EXCLUDED] labour only (vegetation removal/dressing), no material"),
    dict(sl="5", dsr="2.35.2", qty=90.6, unit="Sq.m",
         desc="Providing and injecting chemical emulsion for PRECONSTRUCTIONAL anti termite treatment and creating a chemical barrier under and around the column pits, wall trenches, basement excavation, top surface of plinth filling junction of wall and floor, along the external perimetre of building, expansion joints, surroundings of pipes & conduits etc. complete (plinth area of the building at ground floor only shall be measured) with Aldrin Emulsifiable Concentrate (0.5%)",
         discipline="Civil & Sitework", material="Anti-termite chemical treatment (Aldrin EC 0.5%)", category="Chemical Treatment",
         classification="Chemical treatments > Soil poison > Aldrin EC 0.5%"),
    dict(sl="6", dsr="4.5.10", qty=8.0, unit="Cu.m",
         desc="Providing and laying cement concrete in footings and bases for columns, excluding the cost of centring and shuttering with 1:5:10 (1 cement : 5 coarse sand : 10 graded stone aggregate 40 mm nominal size).",
         discipline="Structural", material="Plain cement concrete 1:5:10", category="Concrete", mix="1:5:10",
         classification="Nominal-mix concrete > Plain cement concrete (nominal mix) > 1:5:10"),
    dict(sl="7", dsr="4.6.11", qty=7.3, unit="Cu.m",
         desc="Providing and laying cement concrete in retaining walls, return walls, walls (any thickness) including attached pilasters, buttresses, plinth, string courses, fillets etc. upto floor two level, excluding the cost of centring and shuttering with 1:5:10 (1 cement : 5 fine sand : 10 graded stone aggregate 40 mm nominal size)",
         discipline="Structural", material="Plain cement concrete 1:5:10", category="Concrete", mix="1:5:10",
         classification="Nominal-mix concrete > Plain cement concrete (nominal mix) > 1:5:10"),
    dict(sl="8", dsr="4.11.1", qty=0.1, unit="Cu.m",
         desc="Providing and laying upto floor two level cement concrete in string or lacing courses, parapets, copings, bed blocks anchor blocks, plain window sills and the like excluding centring and shuttering, etc. with 1:2:4 (1 cement : 2 coarse sand : 4 graded stone aggregate 20 mm nominal size).",
         discipline="Structural", material="Plain cement concrete 1:2:4", category="Concrete", mix="1:2:4",
         classification="Nominal-mix concrete > Plain cement concrete (nominal mix) > 1:2:4"),
    dict(sl="9", dsr="4.24", qty=14.4, unit="Sq.m",
         desc="Providing and laying damp-proof course 40 mm thick with cement concrete 1:2:4 (1 cement : 2 coarse sand : 4 graded stone aggregate 12.5 mm nominal size)",
         discipline="Structural", material="Cement concrete DPC 1:2:4 (40mm)", category="Concrete", mix="1:2:4",
         classification="Nominal-mix concrete > Damp-proof course > 1:2:4"),
    dict(sl="10", dsr="4.27", qty=14.4, unit="Sq.m",
         desc="Applying a coat of residual petroleum bitumen of penetration 80/100 of approved quality using 1.7 Kg. per square metre on damp proof course after cleaning the surface with brushes and finally with a piece of cloth lightly soaked in kerosene oil.",
         discipline="Architectural", material="Petroleum bitumen 80/100 (DPC waterproofing coat)", category="Waterproofing",
         classification="Bituminous products > Paving/waterproofing bitumen > Penetration grade 80/100"),
    dict(sl="11", dsr="5.3", qty=11.3, unit="Cu.m",
         desc="Reinforced cement concrete work in suspended floors, roofs, landings and balconies upto floor two level excluding cost of centring, shuttering, finishing and reinforcement with 1:2:4 (1 cement : 2 coarse sand : 4 graded stone aggregate 20 mm nominal size)",
         discipline="Structural", material="Reinforced cement concrete 1:2:4", category="Concrete", mix="1:2:4",
         classification="Nominal-mix concrete > RCC (nominal mix) > 1:2:4"),
    dict(sl="12", dsr="5.4", qty=1.0, unit="Cu.m",
         desc="Reinforced cement concrete work in shelves upto floor two level excluding the cost of centering and shuttering and reinforcement with 1:2:4 (1 cement : 2 coarse sand : 4 graded stone aggregate 20 mm nominal size).",
         discipline="Structural", material="Reinforced cement concrete 1:2:4", category="Concrete", mix="1:2:4",
         classification="Nominal-mix concrete > RCC (nominal mix) > 1:2:4"),
    dict(sl="13", dsr="5.5", qty=0.6, unit="Cu.m",
         desc="Reinforced cement concrete work in chajjas facias and gutters upto floor two level including throating of plastered drip and moulding excluding cost of centring, shuttering, finishing and reinforcement with 1:2:4 (1 cement : 2 coarse sand : 4 graded stone aggregate 20 mm nominal size).",
         discipline="Structural", material="Reinforced cement concrete 1:2:4", category="Concrete", mix="1:2:4",
         classification="Nominal-mix concrete > RCC (nominal mix) > 1:2:4"),
    dict(sl="14", dsr="5.6.3", qty=1.7, unit="Cu.m",
         desc="Reinforced cement concrete work in lintels, beams, plinth beams and bresummers upto floor two level excluding the cost of centring, shuttering, finishing and reinforcement with 1:2:4 (1 cement : 2 coarse sand : 4 graded stone aggregate 20 mm nominal size).",
         discipline="Structural", material="Reinforced cement concrete 1:2:4", category="Concrete", mix="1:2:4",
         classification="Nominal-mix concrete > RCC (nominal mix) > 1:2:4"),
    dict(sl="15", dsr="5.7.3", qty=0.1, unit="Cu.m",
         desc="Reinforced cement concrete work in columns, pillars, piers, abutments, posts and struts upto floor two level excluding the cost of centring, shuttering, finishing and reinforcement with 1:2:4 (1 cement : 2 coarse sand : 4 graded stone aggregate 20 mm nominal size).",
         discipline="Structural", material="Reinforced cement concrete 1:2:4", category="Concrete", mix="1:2:4",
         classification="Nominal-mix concrete > RCC (nominal mix) > 1:2:4"),
    dict(sl="16", dsr="5.14", desc_common="Centring and shuttering including strutting, proping etc. and removal of form work for :",
         discipline="Structural", material="Formwork (timber/ply shuttering, temporary)", category="Formwork",
         excluded=True,
         sub_items=[
             dict(letter="i", desc="Suspended floors, roofs, landings balconies and chajjas.", qty=108.0, unit="Sq.m"),
             dict(letter="ii", desc="Shelves", qty=17.0, unit="Sq.m"),
             dict(letter="iii", desc="Lintels, beams, plinth beams, girders bressumers and cantilever.", qty=19.0, unit="Sq.m"),
             dict(letter="iv", desc="Columns, pillars, posts and struts.", qty=2.0, unit="Sq.m"),
             dict(letter="v", desc="Vertical and horizontal fins individually or forming box louvers band and facias.", qty=9.0, unit="Sq.m"),
         ]),
    dict(sl="17", dsr="5.29", desc_common="Reinforcement for RCC work including bending binding and placing in position complete.",
         discipline="Structural", material="Steel reinforcement", category="Reinf",
         sub_items=[
             dict(letter="i", desc="Mild steel and medium tensile steel bars.", qty=100.0, unit="Kg.",
                  material="Mild steel/medium tensile steel reinforcement bars",
                  classification="Reinforcement steel (rebar) > Mild steel round bar > Plain round bar Fe-415/Fe-250"),
             dict(letter="ii", desc="Cold twisted bars", qty=1500.0, unit="Kg.",
                  material="Cold twisted deformed (CTD) steel bars",
                  classification="Reinforcement steel (rebar) > Cold-twisted deformed bar > CTD Fe-415",
                  comment="[ASSUMPTION] BoQ gives two alternative quantities '1375.0/1500.0 Kg' with a footnote that the quantity marked * (1500.0) applies for Seismic Zone V; the site metadata block lists Seismic Zone as 'I to IV and V', so the higher (Zone V) quantity of 1500.0 kg was used as the conservative design value. See building_meta.json."),
         ]),
    dict(sl="18", dsr="5.16", qty=0.8, unit="Cu.m",
         desc="Providing and laying upto floor two level RCC in string courses, bands, copings, bed plates, anchor blocks, plain window sills and the like excluding the cost of centering, shuttering, finishing and reinforcement with 1:2:4 (1 cement : 2 coarse sand : 4 graded stone aggregate 20 mm nominal size).",
         discipline="Structural", material="Reinforced cement concrete 1:2:4", category="Concrete", mix="1:2:4",
         classification="Nominal-mix concrete > RCC (nominal mix) > 1:2:4"),
    dict(sl="19", dsr="6.1.14/6.5.1/6.5.2", qty=17.0, unit="Cu.m",
         desc="Brick work with bricks of class designation ___ in foundation and plinth in cement mortar 1:6 (1 cement : 6 coarse sand).",
         discipline="Structural", material="Brick masonry (foundation/plinth, CM 1:6)", category="Masonry", mix="1:6",
         classification="Masonry > Fired clay brick > Common burnt clay brick, class-designated"),
    dict(sl="20", dsr="6.1.14/6.3/6.5.1/6.5.2", qty=40.3, unit="Cu.m",
         desc="Brick work with bricks of class designation ___ in super structure above plinth upto floor two level in cement mortar 1:6 (1 cement : 6 coarse sand).",
         discipline="Structural", material="Brick masonry (superstructure, CM 1:6)", category="Masonry", mix="1:6",
         classification="Masonry > Fired clay brick > Common burnt clay brick, class-designated"),
    dict(sl="21", dsr="6.13/6.21/6.5.1/6.5.2", qty=0.9, unit="Sq.m",
         desc="Brick work 7 cm thick with bricks of class designation ___ in super structure upto floor two level in cement mortar 1:3 (1 cement : 3 coarse sand).",
         discipline="Structural", material="Brick masonry, 7cm thick (CM 1:3)", category="Masonry", mix="1:3",
         classification="Masonry > Fired clay brick > Common burnt clay brick, class-designated"),
    dict(sl="22", dsr="6.18.4/6.21", qty=4.8, unit="Sq.m",
         desc="Half brick masonry with bricks of class designation ___ in foundation & plinth in cement mortar 1:4 (1 cement : 4 coarse sand)",
         discipline="Architectural", material="Half-brick masonry (foundation/plinth, CM 1:4)", category="Masonry", mix="1:4",
         classification="Masonry > Fired clay brick > Common burnt clay brick, class-designated"),
    dict(sl="23", dsr="6.18.4/6.19.1/6.20/6.21.1/6.21.2", qty=18.0, unit="Sq.m",
         desc="Half brick masonry with bricks of class designation ___ in super structure upto floor two level in cement mortar 1:4 (1 cement : 4 coarse sand).",
         discipline="Architectural", material="Half-brick masonry (superstructure, CM 1:4)", category="Masonry", mix="1:4",
         classification="Masonry > Fired clay brick > Common burnt clay brick, class-designated"),
    dict(sl="24", dsr="", qty=3.5, unit="10 Cubic decimetre",
         desc="Providing ___ wood work in frames of doors, windows, clerestory windows and other frames, wrought framed and fixed in position.",
         discipline="Architectural", material="Timber door/window frames (local hardwood)", category="Timber/Joinery",
         classification="Timber > Sawn hardwood > Door/window frame timber"),
    dict(sl="25", dsr="", qty=18.0, unit="Sq.m",
         desc="Providing and fixing 35 mm thick battended and framed door shutters of ___ wood including bright finished or/and black enamelled MS butt hinges with necessary screws.",
         discipline="Architectural", material="Timber battened & framed door shutters (35mm)", category="Timber/Joinery",
         classification="Timber > Joinery > Battened & framed door shutter"),
    dict(sl="26", dsr="9.26.4", qty=4.7, unit="Sq.m",
         desc="Providing and fixing 25 mm thick flush door (for cupboard) shutters core of block board construction with frame of Ist class hard wood and well matched Ist class teak ply veneering with vertical grains or cross bands and face veneer on one face and commercial ply veneering with vertical grains or cross bands and face veneer on other face of shutters, including nickel plated bright finished MS piano hinges with necessary screws.",
         discipline="Architectural", material="Flush door shutter (block-board core, teak ply veneer)", category="Timber/Joinery",
         classification="Timber > Engineered board > Block-board flush door, teak veneered"),
    dict(sl="27", dsr="9.51", qty=20, unit="each",
         desc="Providing 50x50x50 mm 2nd class Teak wood plugs including cutting brick work and fixing in cement mortar 1:3 (1 cement :3 fine sand) and making good the walls etc.",
         discipline="Architectural", material="Teak wood plug (50x50x50mm)", category="Timber/Joinery",
         dims=dict(length_mm=50, width_mm=50, height_mm=50),
         classification="Timber > Fixing accessory > Teak wood plug"),
    dict(sl="28", dsr="", qty=6, unit="each",
         desc="Providing and fixing M.S.oxidised fan light vantilator catch with necessary screws etc. complete.",
         discipline="Architectural", material="MS oxidised fanlight/ventilator catch", category="Ironmongery",
         classification="Ironmongery > Fastener/catch > MS oxidised catch"),
    dict(sl="29", dsr="9.127.3", qty=2, unit="each",
         desc="Providing and fixing 90 mm oxidised M.S. hasp and staple (safety type) with necessaary screws etc. complete.",
         discipline="Architectural", material="MS oxidised hasp & staple, 90mm (safety type)", category="Ironmongery",
         dims=dict(length_mm=90),
         classification="Ironmongery > Fastener > MS hasp & staple"),
    dict(sl="30", dsr="9.218.1", qty=10, unit="Each",
         desc="Providing and fixing aluminium sliding door bolts 300 x 16 mm anodised transparent or dyed to required colour or shade with nuts and screws etc. complete.",
         discipline="Architectural", material="Aluminium sliding door bolt, 300x16mm", category="Ironmongery",
         dims=dict(length_mm=300, diameter_mm=16),
         classification="Ironmongery > Bolt > Aluminium anodised sliding door bolt"),
    dict(sl="31", dsr="", desc_common="Providing and fixing aluminium tower bolts anodised transparent or dyed to required colour or shade with necessary screws etc. complete.",
         discipline="Architectural", material="Aluminium tower bolt", category="Ironmongery",
         sub_items=[
             dict(letter="i", desc="200 x 10 mm", qty=10, unit="Each", dsr="9.219.3", dims=dict(length_mm=200, diameter_mm=10)),
             dict(letter="ii", desc="100 x 10 mm", qty=8, unit="Each", dsr="9.219.5", dims=dict(length_mm=100, diameter_mm=10)),
         ]),
    dict(sl="32", dsr="", desc_common="Providing and fixing aluminium handles anodised transparent or dyed to required colour or shade with necessary screws etc. complete.",
         discipline="Architectural", material="Aluminium handle", category="Ironmongery",
         sub_items=[
             dict(letter="i", desc="100 mm", qty=20, unit="Each", dsr="9.222.2", dims=dict(length_mm=100)),
             dict(letter="ii", desc="75 mm", qty=4, unit="Each", dsr="9.222.3", dims=dict(length_mm=75)),
         ]),
    dict(sl="33", dsr="9.223", qty=10, unit="Each",
         desc="Providing and fixing aluminium hanging floor door stopper anodised transparent or dyed to required colour & shade with necessary screws etc. complete.",
         discipline="Architectural", material="Aluminium hanging floor door stopper", category="Ironmongery",
         classification="Ironmongery > Door stopper > Aluminium anodised"),
    dict(sl="34", dsr="N.S.I.", desc_common="Providing and fixing steel glazed doors, windows and ventilators of standard rolled steel sections, joints mitred and welded with 15x3 mm lugs, 10 cm long, with steel lugs, embedded in cement concrete blocks 15x10x10 cm of 1:3:6 (1 cement : 3 coarse sand : 6 graded stone aggregate 20 mm nominal size) or with wooden plugs and screws or rawl plugs and screws or with fixing clips or with bolts and nuts as required, including providing and fixing of (Pin Head) 3mm thick glass panes with glazing clips and special metal sash putty of approved make complete including applying a priming coat of approved steel primer; excluding the cost of metal beading and other fitting except necessary hinges or pivots as required.",
         discipline="Architectural", material="Steel glazed door/window/ventilator (rolled steel + 3mm glass)", category="Metal Windows/Glazing",
         sub_items=[
             dict(letter="i", desc="Windows - side hung", qty=11.3, unit="Sq.m"),
             dict(letter="ii", desc="Ventilators - centre hung", qty=1.0, unit="Sq.m"),
         ]),
    dict(sl="35", dsr="N.S.I.", qty=21, unit="Each",
         desc="Providing and fixing oxidised mild steel casement window fastners of minimum weight 200 grams to side hung steel windows with necessary welding and machine screws etc. complete.",
         discipline="Architectural", material="MS oxidised casement window fastener (min. 200g)", category="Ironmongery",
         classification="Ironmongery > Fastener > MS casement window fastener"),
    dict(sl="36", dsr="9.224", qty=21, unit="Each",
         desc="Providing and fixing aluminium casement stays anodised transparent or dyed to requird colour and shade with with necessary welding and machine screws etc. complete.",
         discipline="Architectural", material="Aluminium casement stay", category="Ironmongery",
         classification="Ironmongery > Stay > Aluminium anodised casement stay"),
    dict(sl="37", dsr="N.S.I.", qty=66.0, unit="Kg.",
         desc="Providing and welding 20X4 mm M S Guard Flats 10cm c/c in steel windows of standard rolled steel section including a coat of steel peimer as per drawing and specification complete in all respects.",
         discipline="Architectural", material="MS guard flats, 20x4mm (window security bars)", category="Metalwork",
         dims=dict(width_mm=20, thickness_mm=4),
         classification="Structural steel > MS flat bar > Window guard flat 20x4mm"),
    dict(sl="38", dsr="10.14", qty=187.0, unit="Kg.",
         desc="Providing and fixing T - Iron frames for doors, windows and ventilators of mild steel Tee - sections, joints mitred and welded with 15x3 mm lugs 10 cm long embedded in cement concrete blocks 15x10x10 cm of 1:3:6 (1 cement : 3 coarse sand : 6 graded stone aggregate 20 mm nominal size) or with wooden plugs and screws or rawl plugs and screws or with fixing clips or with bolts and nuts as required, including fixing of necessary butt hinges and screws and applying a priming coat of approved steel primer.",
         discipline="Architectural", material="MS T-iron door/window/ventilator frame", category="Metalwork",
         classification="Structural steel > MS Tee section > Door/window frame"),
    dict(sl="39", dsr="10.19", qty=5, unit="Each",
         desc="Providing and fixing MS fan clamp type I of 16 mm dia MS bar bent to shape with hooked ends in RCC slabs during laying including painting the exposed portion of loop, all as per standard design complete.",
         discipline="Structural", material="MS fan clamp, 16mm dia bar (embedded in RCC slab)", category="Metalwork",
         dims=dict(diameter_mm=16),
         classification="Structural steel > MS bar > Fan clamp type I"),
    dict(sl="40", dsr="11.4.2", qty=68.0, unit="Sq.m",
         desc="40 mm thick cement concrete flooring 1:2:4 (1 cement : 2 coarse sand : 4 graded stone aggregate 20.0 mm nominal size) finished with a floating coat of neat cement including cement slurry, rounding off edges and strips etc. but excluding the cost of nosing of steps etc. complete.",
         discipline="Architectural", material="Cement concrete flooring 1:2:4 (40mm)", category="Flooring/Concrete", mix="1:2:4",
         classification="Nominal-mix concrete > Flooring topping > 1:2:4"),
    dict(sl="41", dsr="11.10.1", qty=11.0, unit="Sq.m",
         desc="18 mm thick cement plaster skirting (upto 30 cm height) with cement mortar 1:3 (1 cement : 3 coarse sand) finished with a floating coat of neat cement including rounding of junctions with floors.",
         discipline="Architectural", material="Cement plaster skirting 1:3 (18mm)", category="Plaster", mix="1:3",
         classification="Plaster > Cement plaster > Skirting"),
    dict(sl="42", dsr="11.16.1", qty=9.0, unit="Sq.m",
         desc="40 mm thick marble chips flooring, rubbed and polished to granolithic finish, under layer 31 mm thick cement concrete 1:2:4 (1 cement : 2 coarse sand : 4 graded stone aggregate 12.5 mm nominal size) and top layer 9 mm thick with white black, chocolate, grey yellow or Baroda green marble chips of sizes from 4 mm to 7 mm nominal size laid in cement marble powder mix 3:1 (3 cement : 1 marble powder) by weight in proportion of 4:7 (4 cement marble powder mix : 7 marble chips) by volume including cement slurry etc., complete using dark shade pigment with ordinary cement.",
         discipline="Architectural", material="Marble chips (terrazzo) flooring, 40mm", category="Flooring/Stone",
         classification="Stone flooring > Terrazzo/marble-chip > Granolithic finish"),
    dict(sl="43", dsr="11.20.2", qty=18.0, unit="Mtr.",
         desc="Add or deduct for providing and fixing glass strips in joints of terrazzo/cement concrete floors- 40 mm wide and 6 mm thick.",
         discipline="Architectural", material="Glass strip, joint (40mm x 6mm)", category="Flooring Accessory",
         dims=dict(width_mm=40, thickness_mm=6),
         classification="Glass > Strip/divider > Terrazzo joint strip"),
    dict(sl="44", dsr="12.29.1", qty=65.0, unit="Sq.m",
         desc="Painting top of roofs with bitumen of approved quality at 17 Kg. per 10 square metre impregnated with a coat of coarse sand at 60 dm3 per 10 m2 including cleaning the slab surface with brushes and finally with a piece of cloth lightly soaked in kerosene oil complete with residual type petroleum bitumen of penetration 80/100.",
         discipline="Architectural", material="Petroleum bitumen 80/100 (roof waterproofing coat)", category="Waterproofing",
         classification="Bituminous products > Roof waterproofing bitumen > Penetration grade 80/100"),
    dict(sl="45", dsr="12.35.2", qty=65.0, unit="Sq.m",
         desc="Lime concrete terracing on roofs, average thickness 10 cm laid to fall with 25 mm nominal size brick aggregate and 50% lime mortar 1:2 (1 lime putty : 2 surkhi) rammed and finished with gur and belgiri treatment complete and covered with flat FPS brick tiles of class designation 100 grouted with cement mortar 1:3 (1 cement : 3 fine sand) mixed with 5% crude oil by wt. of cement, over 12 mm layer of cement mortar 1:3 (1 cement : 3 fine sand) and finished neat.",
         discipline="Architectural", material="Lime concrete roof terracing + brick tiles", category="Roofing",
         classification="Roofing > Lime concrete terracing > Brick-aggregate lime concrete"),
    dict(sl="46", dsr="N.S.I.", qty=32.0, unit="Sq.m",
         desc="Providing and laying 25 mm thick burnt clay tiles 250x250x25 mm of approved quality over roofs with 1 cm side joints grouted with CM 1:3 (1 cement : 3 fine sand) over 15 mm thick bed of cement mortar 1:3 (1 cement : 3 fine sand) and finished neat.",
         discipline="Architectural", material="Burnt clay roofing tile, 250x250x25mm", category="Roofing",
         dims=dict(length_mm=250, width_mm=250, thickness_mm=25),
         classification="Roofing > Fired clay tile > Burnt clay roof tile"),
    dict(sl="47", dsr="N.S.I.", qty=46.0, unit="Mtr.",
         desc="Providing gola 15x15 cm in size in cement concrete mix 1:3:6 (1 cement : 3 coarse sand : 6 graded stone aggregate 20 mm nominal size) covered with brick tiles in CM 1:3 (1 cement : 3 coarse sand) as per drawing and specifications complete in all respects.",
         discipline="Architectural", material="Gola (roof edge concrete + brick tile), 15x15cm", category="Roofing",
         dims=dict(width_mm=150, height_mm=150),
         classification="Roofing > Roof edge detail > Concrete gola with brick tile"),
    dict(sl="48", dsr="12.39", qty=3, unit="each",
         desc="Making khurras 45 x 45 cm with average minimum thickness of 5 cm cement concrete 1:2:4 (1 cement : 2 coarse sand : 4 graded stone aggregate 20 mm nominal size) over PVC sheet 1m x 1m x 400 micron, finished with 12 cement plaster 1:3 (1 cement : 3 coarse sand) and a coat of neat cement rounding the edges and making and finishing the outlet complete.",
         discipline="Architectural", material="Khurra (roof outlet): cement concrete + PVC sheet", category="Roof Drainage",
         dims=dict(length_mm=450, width_mm=450, thickness_mm=50),
         classification="Roof drainage > Roof outlet (khurra) > Cement concrete over PVC sheet"),
    dict(sl="49", dsr="12.69.2", qty=10.0, unit="Mtr.",
         desc="Providing and fixing on wallface 100 mm diameter CI rain water pipe including filling the joints with spun yarn soaked in neat cement slurry and cement mortar 1:2 (1 cement : 2 fine sand)",
         discipline="MEP-Plumbing", material="Cast iron rain water pipe, 100mm dia", category="Plumbing/Drainage",
         dims=dict(diameter_mm=100),
         classification="Plumbing > Cast iron pipe > Rain water down-pipe, 100mm"),
    dict(sl="50", dsr="12.71.2", qty=9, unit="Each",
         desc="Providing and fixing 100 mm dia MS holderbat clamps of approved design to CI or SCI rain water pipes embedded in and including cement concrete blocks 10 x 10 x 10 cm of 1:2:4 (1 cement : 2 coarse sand : 4 graded stone aggregate 20 mm nominal size) and cost of cutting holes and making good the walls etc.",
         discipline="MEP-Plumbing", material="MS holderbat clamp, 100mm dia", category="Plumbing/Drainage",
         dims=dict(diameter_mm=100),
         classification="Plumbing > Pipe fixing > MS holderbat clamp"),
    dict(sl="51", dsr="", desc_common="Providing and fixing on wall face CI accessories for rain water pipes including filling the joints with spun yarn soaked in neat cement slurry and cement mortar 1:2 (1 cement : 2 fine sand)",
         discipline="MEP-Plumbing", material="Cast iron rain water pipe accessory", category="Plumbing/Drainage",
         sub_items=[
             dict(letter="i", desc="CI plain head 100 mm dia", qty=3, unit="Each", dsr="12.72.2.2", dims=dict(diameter_mm=100)),
             dict(letter="ii", desc="CI plain shoe - 100 mm dia", qty=3, unit="Each", dsr="12.72.3.2", dims=dict(diameter_mm=100)),
             dict(letter="iii", desc="CI plain bend - 100 mm dia", qty=3, unit="Each", dsr="12.72.1.2", dims=dict(diameter_mm=100)),
         ]),
    dict(sl="52", dsr="13.8.4", qty=220.0, unit="Sq.m",
         desc="12 mm cement plaster of mix 1:6 (1 cement : 6 fine sand)",
         discipline="Architectural", material="Cement plaster 1:6 (12mm)", category="Plaster", mix="1:6",
         classification="Plaster > Cement plaster > General wall plaster"),
    dict(sl="53", dsr="13.9.4", qty=220.0, unit="Sq.m",
         desc="15 mm cement plaster on the rough side of single or half brick wall of mix 1:6 (1 cement : 6 fine sand)",
         discipline="Architectural", material="Cement plaster 1:6 (15mm, rough side)", category="Plaster", mix="1:6",
         classification="Plaster > Cement plaster > General wall plaster"),
    dict(sl="54", dsr="13.25", qty=19.0, unit="Sq.m",
         desc="6 mm cement plaster of mix 1:3 (1 cement : 3 fine sand) finished with a floating coat of neat cement and thick coat of lime wash on top of walls when dry for bearing of RCC slabs and beams.",
         discipline="Structural", material="Cement plaster 1:3 (6mm, bearing course)", category="Plaster", mix="1:3",
         classification="Plaster > Cement plaster > Bearing/finishing coat"),
    dict(sl="55", dsr="5.31/13.24.1", qty=20.0, unit="Sq.m",
         desc="18 mm plastering with terrazzo finish for dado rubbed and polished complete, under layer 12 mm thick cement plaster 1:3 (1 cement : 3 coarse sand) and top layer 6 mm thick white, black, chocolate, grey, yellow or Baroda green marble chips of 3 mm and down size laid in cement marble powder mix 3:1 (3 cement : 1 marble powder) by weight in proportion of 4:7 (4 cement marble powder mix : 7 marble chips) by volume.",
         discipline="Architectural", material="Terrazzo dado plaster, 18mm", category="Flooring/Stone",
         classification="Stone flooring > Terrazzo/marble-chip > Dado finish"),
    dict(sl="56", dsr="13.70.1", qty=155.0, unit="Sq.m",
         desc="Finishing and plastering the exposed surface of RCC with cement mortar 1:3",
         discipline="Structural", material="Cement plaster 1:3 (RCC surface finish)", category="Plaster", mix="1:3",
         classification="Plaster > Cement plaster > Exposed RCC finish"),
    dict(sl="57", dsr="13.73.1", qty=285.0, unit="Sq.m",
         desc="White washing with lime to give an even shade on new work (three or more coats).",
         discipline="Architectural", material="Lime wash (white washing, 3+ coats)", category="Paint/Finish",
         classification="Paints/Finishes > Lime-based wash > White wash"),
    dict(sl="58", dsr="13.81.1", qty=285.0, unit="Sq.m",
         desc="Colour washing such as green, blue or buff to give an even shade on new work (two or more coats) with a base coat of white washing with lime.",
         discipline="Architectural", material="Colour wash (distemper, 2+ coats over lime base)", category="Paint/Finish",
         classification="Paints/Finishes > Lime-based wash > Colour wash"),
    dict(sl="59", dsr="13.81.4", qty=47.0, unit="Sq.m",
         desc="Applying priming coat with ready mixed pink or gray primer of approved brand and manufacture on wood work (hard and soft wood)",
         discipline="Architectural", material="Pink/grey wood primer (priming coat)", category="Paint/Finish",
         classification="Paints/Finishes > Primer > Wood primer"),
    dict(sl="60", dsr="13.84.3", qty=30.0, unit="Sq.m",
         desc="Applying priming coat with readymixed zinc chromate yellow primer of approved brand and manufacture on steelwork (second coat)",
         discipline="Architectural", material="Zinc chromate yellow primer (steelwork, second coat)", category="Paint/Finish",
         classification="Paints/Finishes > Primer > Zinc chromate steel primer"),
    dict(sl="61", dsr="13.94.1", qty=10.0, unit="Mtr.",
         desc="Painting (two or more coats) on rain water, soil, waste and vent pipes and fittings with black anticorrosive bitumastic paint of approved brand and manufacture over and including a priming coat of ready mixed zinc chromate yellow primer on new work on 100 mm diameter pipes.",
         discipline="MEP-Plumbing", material="Black anticorrosive bitumastic paint (pipes)", category="Paint/Finish",
         classification="Paints/Finishes > Anticorrosive coating > Bitumastic paint"),
    dict(sl="62", dsr="", qty=77.0, unit="Sq.m",
         desc="Painting with synthetic enamel paint of approved brand and manufacture to give an even shade in two or more coats on new work in black or chocolate shade over an under coat of suitable shade with ordinary paint of approved brand and manufacture.",
         discipline="Architectural", material="Synthetic enamel paint (2+ coats)", category="Paint/Finish",
         classification="Paints/Finishes > Enamel paint > Synthetic enamel",
         comment="DSR code cell not legible/visible in scan at bottom-right of item 62 row (page 12); left blank rather than guessed."),
    dict(sl="63", dsr="13.101.1", qty=13.0, unit="Sq.m",
         desc="French spirit polishing two or more coats on new works including a coat of wood filler.",
         discipline="Architectural", material="French polish (wood, spirit-based)", category="Paint/Finish",
         classification="Paints/Finishes > Wood polish > French spirit polish"),
    dict(sl="64", dsr="16.1", qty=34.6, unit="Sq.m",
         desc="Making plinth protection 50 mm thick of cement concrete 1:3:6 (1 cement : 3 coarse sand : 6 graded stone aggregate 20 mm nominal size) over 75 mm bed of dry brick ballast 40 mm nominal size well rammed and consolidated and grouted with fine sand, including finishing the top smooth.",
         discipline="Civil & Sitework", material="Cement concrete plinth protection 1:3:6 over brick ballast", category="Concrete", mix="1:3:6",
         dims=dict(thickness_mm=50),
         classification="Nominal-mix concrete > Plinth protection > 1:3:6 over brick ballast"),
]


BUILDING_META = {
    "source_document": "P/Gen(Modified)/BK/10T",
    "institute": "Central Building Research Institute, Roorkee (U.P.)",
    "name_of_work": "Bill of Quantities for Principal's Residence (General-Modified)",
    "schedule": "Schedule 'A'",
    "dsr_edition": "DSR 1989",
    "depth_of_foundation_m": 0.60,
    "plinth_height_m": 0.45,
    "plinth_area_sqm": 90.6,
    "class_designation_of_brick": None,
    "no_of_items": 64,
    "seismic_zone": "I to IV and V",
    "bearing_capacity": "10T/Sq.m and above",
    "notes": [
        "Class Designation of Brick value is illegible/cut off at the bottom edge of the Page 1 scan; left as null rather than guessed.",
        "Handwritten header note on Page 1 reads 'A|X7|I to IV and V', apparently annotating the Seismic Zone applicability.",
        "Item 17(ii) reinforcement quantity is given in the scan as '1375.0/1500.0 Kg' with a footnote that the '*' value (1500.0) applies for Seismic Zone V.",
    ],
}
